# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: 唯独恩典
url: http://scottsuen.github.io
feed: /atom.xml
author_info: <a href="http://scottsuen.github.io/">scottsuen</a>

myblog:
  gavatar: images/2.jpg
  gpname: scottsuen
  linkedin: http://www.linkedin.com/in/scottsuen
  github: https://github.com/scottsuen
  email: mailto:jinming.sun@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
